### ISSUE TITLE
type stubs

### ISSUE THREAD

**Issue by mattsb42-aws** [mattsb42/rhodes#13]
The way that all of the states and choice rules are constructed is nice for DRY, but completely breaks mypy's inspection. :(

I want to fix this, but I'm not sure if it is simpler to write out stub files or just ditch the decorators and do a more OOP-style composition that will be easier for mypy to understand.

**Comment by mattsb42-aws** [comment]
Ideally, it would be awesome if I could modify the interfaces that mypy looks at in the decorators.

Maybe Zope interfaces would be useful here?

**Comment by mattsb42** [comment]
This is even worse for the `__getattr__` magic in `ContextPath`. That one might actually need a stub file.
