### ISSUE TITLE
special state types for the different service integrations

### ISSUE THREAD

**Issue by mattsb42-aws** [mattsb42/rhodes#14]
Step Functions integrates with a variety of AWS services[1]. These, as well as activity workers, all manifest as `Task` states, each with custom configurations.

It would be nice to be able to define these directly without the boilerplate.

- [ ] AWS Lambda
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [x] Integration tests
- [ ] AWS Batch
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [x] Integration tests
- [ ] Amazon DynamoDB
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [x] Integration tests
- [ ] Amazon ECS/Fargate
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [x] Integration tests
- [ ] Amazon SNS
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [x] Integration tests
- [ ] Amazon SQS
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [x] Integration tests
- [ ] AWS Glue
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [x] Integration tests
- [ ] Amazon SageMaker
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [ ] Integration tests
- [ ] Amazon EMR
    - [ ] Framework
    - [ ] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [ ] Integration tests
- [ ] AWS Step Functions
    - [x] Framework
    - [x] API Docs
    - [ ] Input Validation
    - [ ] Troposphere integration
    - [x] Integration tests

ex:
```python
boilerplate = Task(
    "MyChildStateMachine",
    Resource="arn:aws:states:::states:startExecution.sync",
    Parameters=dict(
        Input={"Comment": "Hello world!"},
        StateMachineArn="arn:aws:states:us-east-1:123456789012:stateMachine:HelloWorld"
    )
)

less_boilerplate = ChildStateMachine(
    "MyChildStateMachine",
    sync=True,
    Input={"Comment": "Hello world!"},
    StateMachineArn="arn:aws:states:us-east-1:123456789012:stateMachine:HelloWorld"
)
```

-----------------

## Issues

Collecting issues to investigate here for lack of a better place. I need to test these to determine the actual behavior.

### [Lambda](https://docs.aws.amazon.com/step-functions/latest/dg/connect-lambda.html)

- [ ] The docs indicate that `InvocationType` is a valid input, but that seems unlikely to me given that the invocation type should seem to be indicated by the SFn integration pattern, not by state parameters.

### [Step Functions](https://docs.aws.amazon.com/step-functions/latest/dg/connect-stepfunctions.html)

- [x] The docs indicate that all parameter names are camelCase, but the states language requires that they are PascalCase. #45 
   - one note here: the ECS API values are camelCase but the states language docs are adjusted to show that states language requires PascalCase
- [ ] The docs indicate that `Name` is accepted as a parameters. I am suspicious of this actually being valid, but I'm not ruling it out yet.
- [ ] The docs indicate that `Input` MUST be a string, but the states language accepts objects and JSON-Path values.

### All

- [ ] Anywhere that a service integration accepts structured data with known field names, those field names MUST also be in PascalCase regardless of what the underlying service expects.

[1] https://docs.aws.amazon.com/step-functions/latest/dg/concepts-service-integrations.html

**Comment by mattsb42** [comment]
This is a WIP on the "services" branch. ...this turned out to be a lot more complicated than I expected. x_x

**Comment by mattsb42** [comment]
still WIP, but I've merged the roughed-out framework into master for the 0.3.0 release.

**Comment by mattsb42** [comment]
On 2019-11-19, Step Functions launched service integration support for Amazon EMR.

https://docs.aws.amazon.com/step-functions/latest/dg/connect-emr.html

**Comment by mattsb42** [comment]
closing down project as discussed in #164
