### ISSUE TITLE
simplify input/output/etc paths

### ISSUE THREAD

**Issue by mattsb42-aws** [mattsb42/rhodes#15]
Despite working with Step Functions for several years, something that has never really managed to penetrate my brain is the role that all of the different path values play in forming the state machine execution body[1]. I assume that I am not the only one who encounters this issue.

It would be nice to have some sort of interface that makes this simpler to understand. I'm not sure yet what that would look like.

[1] https://docs.aws.amazon.com/step-functions/latest/dg/concepts-input-output-filtering.html

**Comment by mattsb42** [comment]
closing down project as discussed in #164
