### ISSUE TITLE
programmatic jsonpath

### ISSUE THREAD

**Issue by mattsb42** [mattsb42/rhodes#3]
Requiring hand-coding of strings is prone to error. We can get around this most places in Rhodes by allowing use of Rhodes or Troposphere objects or `datetime` objects for timestamp choice values. But there are a lot of places where Amazon States Language accepts JSONPath strings. It would be nice to be able to define those programmatically in a way that will help developers avoid errors.

**Comment by mattsb42-aws** [comment]
One possible solution to this would be to override `__getattr__` on the new `WorkflowPath` (name TBD) #10 so you could have something along the lines of:

```
str(WorkflowPath().path.to.result) == "$.path.to.result"
```

**Comment by mattsb42** [comment]
At least for now, I think I'm going to say if someone wants to do this, they should piggy-back on `jsonpath_rw` or use Enums.
