### ISSUE TITLE
state output selector

### ISSUE THREAD

**Issue by mattsb42** [mattsb42/rhodes#32]
The states language support selecting which part of the execution body to use as input for a state (`InputPath`), selecting where in the execution body to place the output from a state (`ResultPath`), and which part of the resulting execution body to send to the next state (`OutputPath`), but it does not have any way to specify a part of the state output to assign to the `ResultPath`.

For states that you fully control, this is fine, you just make the state output whatever you want to send to the `ResultPath`. However, for service integrations[1] this becomes more complicated because you do *not* control the full output. Instead, the service integration tasks send back a response that contains not only the response from the service but also a lot of metadata. This is great as a way of communicating details from the integrated service to your state machine, but adds a lot of extra data if you just want the response payload.

As a workaround to this, I want to add a pseudo-parameter to `State` that will result in `to_dict` injecting a `Pass` state that performs this modification.

For example:

```python
AwsLambda(
    "foo",
    FunctionName="bar",
    ResultPath=JsonPath("$.baz"),
    Next="wat"
)
```

will result in:

```json
{
    "foo":{
        "Type": "Task",
        "Resource": "arn:aws:states:::lambda:invoke",
        "Next": "wat",
        "ResultPath": "$.baz",
        "Parameters": {
            "FunctionName": "bar",
            "InvocationType": "RequestResponse"
        }
    }
}
```

But the lambda service integration returns a huge response that contains many things. The piece we're actually probably interested in is the response payload, located at `$.Payload` in the response.

So, to work around this, if I add `ResultSource` to indicate what part of my state output I actually want to feed out, then `to_dict` can inject a `Pass` state that does the desired trimming:

```python
AwsLambda(
    "foo",
    FunctionName="bar",
    ResultSource=JsonPath("@.Payload"),
    ResultPath=JsonPath("$.baz"),
    Next="wat"
)
```

would result in:

```json
{
    "foo":{
        "Type": "Task",
        "Resource": "arn:aws:states:::lambda:invoke",
        "Next": "4caee30f-5086-47e6-9376-d18171ded858",
        "ResultPath": "$.baz",
        "Parameters": {
            "FunctionName": "bar",
            "InvocationType": "RequestResponse"
        }
    },
    "4caee30f-5086-47e6-9376-d18171ded858": {
        "Type": "Pass",
        "InputPath": "$.baz.Payload",
        "ResultPath": "$.baz",
        "Next": "wat"
    }
}
```

[1] https://docs.aws.amazon.com/step-functions/latest/dg/concepts-service-integrations.html

**Comment by mattsb42** [comment]
This will be slightly complicated by the fact that currently `State.to_dict()` only returns the contents, not the name.

**Comment by mattsb42-aws** [comment]
Another pattern that might make sense for this is to instead add a method to `State` that results in this.

ex:

```python
foo = AwsLambda(
    "foo",
    FunctionName="bar",
    ResultPath=JsonPath("$.baz"),
    Next="wat"
)
foo_adjuster = foo.promote_result("@.Payload")
```
