### ISSUE TITLE
service intergration helper parameter names are incorrect

### ISSUE THREAD

**Issue by mattsb42-aws** [mattsb42/rhodes#45]
I was afraid this would be the case...

The Step Functions service integration docs[1] never actually state the exact names that they expect in the `Parameters` value. Instead, they link to each of the service docs for the API that the service integration calls and identifies the fields that are passed along. Unfortunately, these two things are not always equivalent. :(

For example, the Step Functions service integration page[2] states that the `stateMachineArn`, `name`, and `input` parameters are supported. However, the examples then show `StateMachineArn`, `Name`, and `Input`.

If the field names in the examples are used (ie: PascalCase), the state machine creation works. If the field names as stated in the documentation proper are used, the state machine creation fails.

Not all of the service integrations have examples for all supported fields. I could just try all of the integrations and see what works and what breaks, but it would be nice to find out the (presumably consistent) pattern that Step Functions is using to transform these to and from their `Parameters` input fields.

[1] https://docs.aws.amazon.com/en_pv/step-functions/latest/dg/concepts-service-integrations.html
[2] https://docs.aws.amazon.com/en_pv/step-functions/latest/dg/connect-stepfunctions.html

**Comment by mattsb42** [comment]
I'm not 100% on what's going on with EMR, but looking through these again, I *think* that Step Functions is ironically the only integration that is affected by this.
