### ISSUE TITLE
make step functions linking automatic

### ISSUE THREAD

**Issue by mattsb42-aws** [mattsb42/rhodes#60]
The Step Functions service integration provides a way to indicate to nested workflows what other workflow execution started them[1]. I can indicate this using `Parameter` fields now like so[2], but this seems like something that should be automatically set for every nested workflow call.

[1] https://docs.aws.amazon.com/step-functions/latest/dg/connect-stepfunctions.html
[2] `AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID=ContextPath().Execution.Id`

**Comment by mattsb42** [comment]
closing down project as discussed in #164
